### ISSUE TITLE
Bug with ofxSimpleHTTP example

### ISSUE THREAD

**Issue by mantissa** [armadillu/ofxSimpleHttp#10]
In OF 9.3 on OS X 10.10.5, the callback function doesn't move the downloaded file to the completed folder and reports "file was not downloaded???!"

```
ofDirectory f;
f.open( r.absolutePath );
if(f.exists()){
  //...
} ;
```

Works when f is of type ofFile

```
ofFile f;
f.open( r.absolutePath );
if(f.exists()){
  //...
} ;
```

**Comment by armadillu** [comment]
thx for the report! fixed in 4f60f8714e1bed29cf0fe29bf61854a38159588c
