### ISSUE TITLE
iOS support: remove xxh_x86dispatch

### ISSUE THREAD

**Issue by artificiel** [armadillu/ofxSimpleHttp#13]
the addon did not compile on iOS because x86dispatch is not supported on ARM, however simply removing the references to xxh_x86dispatch.c and .h in the Xcode project allowed compilation.

maybe there are consequences to removing those files but it works properly (tested on iOS 14.4.2 vs a variety of http and https servers (including ofxWebServer) to download images on the local device). not sure if there's a clean way to instruct the addon not to use these files on iOS.

**Comment by armadillu** [comment]
if it builds and runs ok, it's probably not an issue. the xxh lib is used for checksums though, so unless you are using that feature (ofxchecksum), it really won't affect you. Looking through, it seems that file is just to speed up checksums on x86 processors using AVX2 & co, so yep, just removing it from the xcode project should do.

**Comment by artificiel** [comment]
ok great! it would be ideal if the addon could be tweaked to include x86dispatch only on x86/64 (not sure if that's doable in addon_config?) -- or add a note about the removal maneuver in the README for future iOS devs (hacking blindly at problematic stuff is something that i do spontaneously, but not everyone has the same reflexes).

**Comment by armadillu** [comment]
its probably easier/cleaner to modify x86dispatch slightly to not err out at compile time, just ifdef the ARM architecture away. I'll have a look
